name: Lint Dockerfile
on: [push, pull_request, workflow_dispatch]

jobs:
  hadolint:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # 2.4.0

      - name: Run hadolint
        uses: hadolint/hadolint-action@d7b38582334d9ac11c12021c16f21d63015fa250 # 1.6.0
        with:
          dockerfile: Dockerfile
