name: Lint Dockerfile
on: [push, pull_request, workflow_dispatch]

jobs:
  hadolint:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # 2.4.0

      - name: Run hadolint
        uses: hadolint/hadolint-action@d7b38582334d9ac11c12021c16f21d63015fa250 # 1.6.0
        with:
          dockerfile: Dockerfile
