name: Lint Dockerfile
on: [push, pull_request, workflow_dispatch]

jobs:
  hadolint:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@1e204e9a9253d643386038d443f96446fa156a97 # 2.3.4

      - name: Run hadolint
        uses: hadolint/hadolint-action@d7b38582334d9ac11c12021c16f21d63015fa250 # 1.6.0
        with:
          dockerfile: Dockerfile
